### ISSUE TITLE
GoPro 5 session

### ISSUE THREAD

**Issue by dmrkonjic** [KonradIT/gopro-py-api#111]
**Describe the bug**
started into part to waking up gopro but didn't take picture.
If you have any ideas?

>>> from goprocam import GoProCamera, constants
>>> goproCamera = GoProCamera.GoPro()
Waking up...
>>> goproCamera.shoot_video(10)
Waking up...
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/gopro-py-api/goprocam/GoProCamera.py", line 152, in sendCamera
    self.getPassword() + value_notempty)
  File "/root/gopro-py-api/goprocam/GoProCamera.py", line 112, in _request
    return urllib.request.urlopen(uri, timeout=_timeout, context=_context).read().decode("utf-8")
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/gopro-py-api/goprocam/GoProCamera.py", line 516, in shoot_video
    self.mode(constants.Mode.VideoMode)
  File "/root/gopro-py-api/goprocam/GoProCamera.py", line 339, in mode
    self.sendCamera("CM", mode)
  File "/root/gopro-py-api/goprocam/GoProCamera.py", line 154, in sendCamera
    print("Error code:" + str(error.code) +
AttributeError: 'URLError' object has no attribute 'code'

**Comment by KonradIT** [comment]
This one's weird, was the camera on? Try putting the MAC identifier in the constructor as well as the camera type: GoProCamera.GoPro(constants.gpcontrol, mac_address=[your Mac address]
