### ISSUE TITLE
[Hero5 Black] no file names

### ISSUE THREAD

**Issue by zactodd** [KonradIT/gopro-py-api#157]
**Describe the bug**
After taking photos the api is unable to download the last photo. The photo is taken it just can be downloaded.
I am also unable to delete the photo.

**To Reproduce**
>>> from goprocam import GoProCamera, constants
>>> hero5 = GoProCamera.GoPro()
HERO5 Black
HD5.02.02.60.00
Camera successfully connected!
>>> hero5.take_photo()
''
>>> hero5.getMedia()
''
>>> hero5.downloadLastMedia()
filename: 
size: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tutor/anaconda3/envs/RP/lib/python3.7/site-packages/goprocam/GoProCamera.py", line 813, in downloadLastMedia
    self.getMedia(), custom_filename)
  File "/home/tutor/anaconda3/envs/RP/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/tutor/anaconda3/envs/RP/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/tutor/anaconda3/envs/RP/lib/python3.7/urllib/request.py", line 510, in open
    req = Request(fullurl, data)
  File "/home/tutor/anaconda3/envs/RP/lib/python3.7/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/home/tutor/anaconda3/envs/RP/lib/python3.7/urllib/request.py", line 354, in full_url
    self._parse()
  File "/home/tutor/anaconda3/envs/RP/lib/python3.7/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''

**Expected behavior**
Finding and downloading the photo.

**Desktop (please complete the following information):**
 - OS:  Both Windows 10 and Ubuntu 20.04

**Comment by zactodd** [comment]
Fixed by updating the Hero 5 black via the go pro app.
