### ISSUE TITLE
Hero3+, error concatentating strings in overview

### ISSUE THREAD

**Issue by jimdavcon** [KonradIT/gopro-py-api#167]
**Describe the bug**
Using examples with Hero3+, getting TypeErrors in call to overview method. Seems to complete the wifi connect and infoCamera and getStatus both complete successfully.

**To Reproduce**
Using this code with miniconda:

`from goprocam import GoProCamera
from goprocam import constants

print("get object...")
gpCam = GoProCamera.GoPro(constants.auth)

print("get overview...")
gpCam.overview()`

**Screenshots**
Above python script produces the following output..

>python go2.py
get object...
Connected to 10.5.5.9
get overview...
camera overview
current mode: Video
current video resolution: 720p
current photo resolution: 5mp m
Traceback (most recent call last):
  File "go2.py", line 8, in <module>
    gpCam.overview()
  File "C:\Users\Jim\miniconda3\lib\site-packages\goprocam\GoProCamera.py", line 1512, in overview
    print("current timelapse interval: " + self.parse_value(constants.Hero3Status.TimeLapseInterval,
TypeError: can only concatenate str (not "NoneType") to str

>

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox
 - Conda packages and versions listed below:
>conda list
# packages in environment at C:\Users\Jim\miniconda3:
#
# Name                    Version                   Build  Channel
beautifulsoup4            4.9.3                    pypi_0    pypi
brotlipy                  0.7.0           py38h2bbff1b_1003
ca-certificates           2021.1.19            haa95532_0
certifi                   2020.12.5        py38haa95532_0
cffi                      1.14.4           py38hcd4344a_0
chardet                   4.0.0           py38haa95532_1003
conda                     4.9.2            py38haa95532_0
conda-package-handling    1.7.2            py38h76e460a_0
console_shortcut          0.1.1                         4
cryptography              3.3.1            py38hcd4344a_0
goprocam                  4.1.0                    pypi_0    pypi
idna                      2.10               pyhd3eb1b0_0
menuinst                  1.4.16           py38he774522_1
openssl                   1.1.1i               h2bbff1b_0
pip                       20.3.3           py38haa95532_0
powershell_shortcut       0.0.1                         3
pycosat                   0.6.3            py38h2bbff1b_0
pycparser                 2.20                       py_2
pyopenssl                 20.0.1             pyhd3eb1b0_1
pysocks                   1.7.1            py38haa95532_0
python                    3.8.5                h5fd99cc_1
python_abi                3.8                      1_cp38    conda-forge
pywin32                   227              py38he774522_1
requests                  2.25.1             pyhd3eb1b0_0
ruamel_yaml               0.15.87          py38he774522_1
setuptools                52.0.0           py38haa95532_0
six                       1.15.0           py38haa95532_0
soupsieve                 2.1                      pypi_0    pypi
sqlite                    3.33.0               h2a8f88b_0
tqdm                      4.56.0             pyhd3eb1b0_0
uritools                  3.0.0            py38h32f6830_2    conda-forge
urllib3                   1.26.3             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.36.2             pyhd3eb1b0_0
win_inet_pton             1.1.0            py38haa95532_0
wincertstore              0.2                      py38_0
yaml                      0.2.5                he774522_0
zlib                      1.2.11               h62dcd97_4

>

**Comment by pgregg88** [comment]
I get a similar error in a linux environment

>>> from goprocam import GoProCamera
>>> from goprocam import GoProCamera
>>> print("get object...")
get object...
>>> gpCam = GoProCamera.GoPro(constants.auth)
Connected to 10.5.5.9
>>> gpCam.overview()
camera overview
current mode: Photo
current video resolution: WVGA
current photo resolution: 7mp w
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.virtualenvs/goprocam/lib/python3.6/site-packages/goprocam/GoProCamera.py", line 1513, in overview
TypeError: must be str, not NoneType
>>>
