### ISSUE TITLE
delete in gopro3+ retuerns error

### ISSUE THREAD

**Issue by lavitan** [KonradIT/gopro-py-api#23]
>>> gpCam.delete("last")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/goprocam/GoProCamera.py", line 303, in delete
    print(self.sendCamera("DL"))
  File "/usr/local/lib/python3.6/site-packages/goprocam/GoProCamera.py", line 113, in sendCamera
    urllib.request.urlopen('http://10.5.5.9/camera/' + param + '?t=' + self.getPassword() + value_no      tempty, timeout=5).read()
UnboundLocalError: local variable 'value_notempty' referenced before assignment

**Comment by KonradIT** [comment]
can you try running the API from source?

**Comment by lavitan** [comment]
same response

**Comment by z3r63ru5** [comment]
I have the same error (pip3 install goprocam) 
The problem is a typo in line 108 ("value_notem**tp**y") ...

Regards,
DKK

**Comment by lavitan** [comment]
thank you, it works
